name: 'Backend CI Action'
description: 'バックエンドプロジェクトのCI処理（テスト、ビルド、静的解析）'

# Composite Action として定義
runs:
  using: 'composite'
  steps:
    # Go のセットアップ
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    # Go modules のキャッシュ
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum', 'backend/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    # 依存関係のダウンロード
    - name: Download dependencies
      run: go mod download
      shell: bash
      working-directory: backend
    
    # 静的解析実行
    - name: Run go vet
      run: go vet ./...
      shell: bash
      working-directory: backend
    
    # テスト実行（カバレッジ付き）
    - name: Run tests with coverage
      run: go test -v -race -coverprofile=coverage.out ./...
      shell: bash
      working-directory: backend
    
    # カバレッジレポート表示
    - name: Display coverage
      run: go tool cover -func=coverage.out
      shell: bash
      working-directory: backend
    
    # ビルド実行
    - name: Build application
      run: go build -v ./...
      shell: bash
      working-directory: backend
    
    # 追加のバックエンド固有処理
    - name: Security scan
      run: echo "Security scan completed for backend"
      shell: bash
      
    - name: Performance benchmark
      run: echo "Performance benchmark completed for backend"
      shell: bash