name: 'Backend Security Action'
description: 'バックエンドのセキュリティスキャン処理'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum', 'backend/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download
      shell: bash
      working-directory: backend

    - name: Run security scan (placeholder)
      run: echo "🔒 Security scan simulated - would run gosec, etc."
      shell: bash

    - name: Check for vulnerable dependencies
      run: echo "🛡️ Dependency vulnerability check simulated"
      shell: bash

    - name: Security results
      run: echo "🔐 Security scan completed successfully"
      shell: bash