name: 'Backend Lint Action'
description: 'バックエンドの静的解析処理'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum', 'backend/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download
      shell: bash
      working-directory: backend

    - name: Run go vet
      run: go vet ./...
      shell: bash
      working-directory: backend

    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted"
          exit 1
        fi
      shell: bash
      working-directory: backend

    - name: Lint results
      run: echo "✅ Static analysis completed successfully"
      shell: bash